import Link from "next/link";
import { Arrow, Layout, PageHero } from "../components/site-shell";

const values = [["Integrity", "Transparent and responsible business relationships."], ["Quality", "Product consistency and customer requirements at the centre."], ["Reliability", "Dependable supply and responsive communication."], ["Innovation", "Better products, processes, and solutions."], ["Safety", "Responsible chemical handling and safe business practices."], ["Sustainability", "Resource-conscious solutions and long-term environmental goals."], ["Partnership", "Strong relationships that create stronger businesses."]];

export default function About() {
  return <Layout>
    <PageHero eyebrow="About NexaChem" title={<>Empowering industrial growth across <em>UAE & GCC.</em></>} text="NexaChem Industrial Solutions Co. is a premier B2B chemical trading, distribution, and logistics organization dedicated to supporting manufacturing, energy, and water infrastructure across the Middle East." actions={<Link className="button primary" href="/contact">Connect with our team <Arrow /></Link>} />
    <section className="section"><div className="section-inner split">
      <div><p className="eyebrow">Corporate profile</p><h2 className="statement">A regional partner for <strong>essential supply.</strong></h2></div>
      <div className="split-copy"><p>NexaChem connects industrial customers with the raw materials and supply support their operations depend on. Our work brings chemical trading, distribution, logistics, and product knowledge together to serve customers across the UAE and wider GCC.</p><p>We support the manufacturing, energy, construction, and water sectors with a focus on dependable supply, certified product quality, responsive service, and responsible chemical handling.</p></div>
    </div></section>
    <section className="section corporate-purpose"><div className="section-inner split">
      <div><p className="eyebrow light">Our purpose</p><h2 className="section-title">Supporting regional industrial strategy.</h2></div>
      <div className="split-copy"><p>NexaChem plays a vital role in the GCC manufacturing ecosystem by helping maintain seamless raw material supply chains, certified chemical quality, and dependable hazmat logistics.</p><p>From high-volume Caustic Soda for manufacturing plants in Dubai, to TEG Glycols for oilfield operators in Abu Dhabi and Polycarboxylate Superplasticizers for infrastructure projects in KSA, we bring technical care and commercial reliability to each supply relationship.</p></div>
    </div></section>
    <section className="section blue-section"><div className="section-inner"><p className="eyebrow">Our direction</p><div className="split"><div><h2 className="section-title">Our mission</h2><p className="section-lead">To provide high-quality chemical products and dependable solutions that help customers operate more efficiently, safely, and sustainably.</p></div><div><h2 className="section-title">Our vision</h2><p className="section-lead">To become a trusted regional chemical solutions partner recognized for quality, responsible supply, and customer-focused service.</p></div></div><div className="value-grid">{values.map(([title, text], i) => <article className="value-card" key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section"><div className="section-inner split"><div className="image-panel tanks"><p className="floating-note">Reliable supply chains help keep essential industries moving.</p></div><div className="split-copy"><p className="eyebrow">How we work</p><h2 className="section-title">Supply built around customer needs.</h2><p>Chemical supply is more than moving products from one location to another. Customers need consistent quality, clear technical information, reliable availability, responsible handling, and timely delivery.</p><p>We bring these priorities together through practical communication and long-term partnerships, helping customers source the materials that keep their operations moving.</p><p><strong>NexaChem Industrial Solutions Co.</strong></p></div></div></section>
  </Layout>;
}
