import Link from "next/link";
import { Arrow, Layout, PageHero } from "./components/site-shell";

const strengths = [["01", "Dependable sourcing", "Careful supplier coordination for critical raw materials and industrial chemicals."], ["02", "Quality in focus", "Product requirements and documentation considered from the first enquiry."], ["03", "Regional logistics", "Responsive distribution and hazmat logistics for UAE and GCC operations."], ["04", "A practical partner", "Commercial and technical communication shaped around your operation."]];
const categories = [["Industrial chemicals", "Core raw materials for manufacturing and processing."], ["Water treatment", "Chemicals that support water infrastructure and treatment systems."], ["Oilfield & energy", "Supply for demanding energy and oilfield applications."], ["Construction", "Materials supporting concrete and regional infrastructure projects."]];

export default function Home() {
  return <Layout>
    <PageHero eyebrow="NexaChem Industrial Solutions Co. · UAE & GCC" title={<>Essential chemistry. <em>Regional impact.</em></>} text="A chemical trading, distribution, and logistics partner supporting manufacturing, energy, and water infrastructure across the Middle East." actions={<><Link className="button primary" href="/products">Explore our products <Arrow /></Link><Link className="button secondary" href="/contact">Discuss a requirement</Link></>} />
    <section className="home-intro section"><div className="section-inner home-intro-inner"><div><p className="eyebrow">Built for industry</p><h2 className="section-title">Keeping essential materials moving across the region.</h2></div><div className="split-copy"><p>NexaChem connects businesses with dependable chemical supply, product knowledge, and coordinated logistics. We work alongside our customers to support operations where availability, quality, and safe handling matter every day.</p><Link className="text-link" href="/about">Discover NexaChem <Arrow /></Link></div></div><div className="section-inner home-metrics"><div><strong>UAE</strong><span>Headquartered regional focus</span></div><div><strong>GCC</strong><span>Supporting regional industries</span></div><div><strong>01</strong><span>Connected supply partner</span></div></div></section>
    <section className="home-purpose"><div className="home-purpose-image"><div className="purpose-stamp"><span>SUPPLYING</span><strong>Industry<br/>in motion.</strong><span>UAE · GCC</span></div></div><div className="home-purpose-copy"><p className="eyebrow light">Our purpose</p><h2>Supporting the region’s industrial ambitions.</h2><p>We help strengthen the GCC manufacturing ecosystem through raw material supply chains, certified chemical quality, and dependable hazmat logistics.</p><p>From Caustic Soda for manufacturers in Dubai to TEG Glycols for oilfield operators in Abu Dhabi and construction admixtures for projects in KSA, NexaChem brings technical care and commercial reliability to regional supply.</p><Link className="button light-button" href="/about">Our corporate profile <Arrow /></Link></div></section>
    <section className="section home-portfolio"><div className="section-inner"><div className="section-heading-row"><div><p className="eyebrow">Our portfolio</p><h2 className="section-title">Materials for the work that moves us forward.</h2></div><Link className="text-link" href="/products">Browse the catalogue <Arrow /></Link></div><div className="home-category-grid">{categories.map(([title, text], i) => <Link className="home-category" href="/products" key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div><Arrow /></Link>)}</div></div></section>
    <section className="section home-strengths"><div className="section-inner"><p className="eyebrow">A reliable supply relationship</p><div className="section-heading-row"><h2 className="section-title">Consistency behind every delivery.</h2><p className="section-lead">Good supply takes more than availability. It takes careful coordination, clear information, and attention to how materials move.</p></div><div className="home-strength-grid">{strengths.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="home-contact"><div><p className="eyebrow light">Let’s get to work</p><h2>Tell us what your operation needs.</h2></div><Link className="button primary" href="/contact">Start an enquiry <Arrow /></Link></section>
  </Layout>;
}
