export const products = [
  // 1. Industrial Chemicals
  {
    id: "caustic-soda-flakes",
    name: "Caustic Soda Flakes / Lye",
    chemicalName: "Sodium Hydroxide",
    cas: "1310-73-2",
    formula: "NaOH",
    category: "Industrial Chemicals",
    grade: "Industrial Grade (99% Min)",
    purity: "99.0%",
    form: "Solid Flakes / Micropearls",
    packaging: "25kg PP Bags / 1,000kg Jumbo Bags",
    industries: ["Manufacturing", "Water Treatment", "Detergents", "Paper & Pulp", "Steel & Galvanizing"],
    applications: ["pH adjustment", "Chemical manufacturing", "Soap & detergent production", "Metal cleaning & degreasing", "Alumina processing"],
    hazards: "Class 8 Corrosive",
    unNumber: "UN 1823",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "High-purity solid Sodium Hydroxide flakes produced to strict technical standards. Essential for chemical synthesis, saponification, pH neutralization, and industrial cleaning across Saudi Arabian manufacturing complexes."
  },
  {
    id: "hydrogen-peroxide-50",
    name: "Hydrogen Peroxide 50%",
    chemicalName: "Hydrogen Peroxide",
    cas: "7722-84-1",
    formula: "H2O2",
    category: "Industrial Chemicals",
    grade: "Industrial / Technical Grade",
    purity: "50.0% Solution",
    form: "Clear Liquid",
    packaging: "30kg Drums / 1,100kg IBC Tanks / ISO Tanker Bulk",
    industries: ["Water Treatment", "Textiles", "Paints & Coatings", "Pharmaceuticals", "Manufacturing"],
    applications: ["Industrial bleaching", "Wastewater oxidation", "Disinfection", "Chemical synthesis", "Odor control"],
    hazards: "Class 5.1 Oxidizer / Class 8 Corrosive",
    unNumber: "UN 2014",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "Powerful eco-friendly oxidizing agent that decomposes into water and oxygen. Widely utilized in effluent treatment, textile processing, and chemical oxidation."
  },
  {
    id: "methanol",
    name: "Methanol (Methyl Alcohol)",
    chemicalName: "Methanol",
    cas: "67-56-1",
    formula: "CH3OH",
    category: "Industrial Chemicals",
    grade: "Technical / Petrochemical Grade",
    purity: "99.85% Min",
    form: "Clear Colorless Liquid",
    packaging: "200L Steel Drums / ISO Tank Container / Bulk Tanker",
    industries: ["Petrochemicals", "Oil & Gas", "Paints & Coatings", "Construction"],
    applications: ["Formaldehyde production", "Gas hydrate inhibition", "Chemical solvent", "Biodiesel feedstock", "Anti-freeze formulation"],
    hazards: "Class 3 Flammable Liquid / Class 6.1 Toxic",
    unNumber: "UN 1230",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "High-grade industrial solvent and vital chemical building block for petrochemical processing and offshore oilfield hydrate control."
  },
  {
    id: "acetone",
    name: "Acetone Pure",
    chemicalName: "Propan-2-one",
    cas: "67-64-1",
    formula: "C3H6O",
    category: "Industrial Chemicals",
    grade: "Technical Grade",
    purity: "99.5% Min",
    form: "Volatile Colorless Liquid",
    packaging: "160kg Steel Drums / IBC / Bulk Tanker",
    industries: ["Paints & Coatings", "Pharmaceuticals", "Manufacturing", "Personal Care"],
    applications: ["Industrial solvent", "Resin formulation", "Equipment flushing", "Pharmaceutical extraction", "Nail polish remover base"],
    hazards: "Class 3 Highly Flammable",
    unNumber: "UN 1090",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Fast-evaporating polar solvent ideal for degreasing, resin thinning, and laboratory extractions."
  },
  {
    id: "toluene",
    name: "Toluene Technical",
    chemicalName: "Methylbenzene",
    cas: "108-88-3",
    formula: "C7H8",
    category: "Industrial Chemicals",
    grade: "Industrial Grade",
    purity: "99.7% Min",
    form: "Clear Liquid",
    packaging: "179kg Drums / ISO Tank",
    industries: ["Paints & Coatings", "Petrochemicals", "Detergents", "Construction"],
    applications: ["Paint thinner", "Adhesive production", "Chemical intermediate", "Rubber solvent"],
    hazards: "Class 3 Flammable Liquid",
    unNumber: "UN 1294",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Aromatic hydrocarbon solvent used extensively in industrial coatings, adhesives, and chemical synthesis."
  },
  {
    id: "xylene-mixed",
    name: "Xylene (Mixed Isomers)",
    chemicalName: "Dimethylbenzene",
    cas: "1330-20-7",
    formula: "C8H10",
    category: "Industrial Chemicals",
    grade: "Industrial Grade",
    purity: "98.5% Min",
    form: "Clear Liquid",
    packaging: "180kg Drums / ISO Tank",
    industries: ["Paints & Coatings", "Oil & Gas", "Manufacturing"],
    applications: ["High-build coating solvent", "Alkyd resin solvent", "Industrial degreasing", "Pesticide carrier"],
    hazards: "Class 3 Flammable Liquid",
    unNumber: "UN 1307",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "High-performance aromatic solvent designed for heavy-duty protective paints, epoxy thinners, and industrial applications."
  },
  {
    id: "acetic-acid-glacial",
    name: "Glacial Acetic Acid 99.8%",
    chemicalName: "Ethanoic Acid",
    cas: "64-19-7",
    formula: "CH3COOH",
    category: "Industrial Chemicals",
    grade: "Technical / Food Grade Available",
    purity: "99.8% Min",
    form: "Colorless Liquid",
    packaging: "30kg HDPE Drums / 1,050kg IBC",
    industries: ["Food & Beverage", "Textiles", "Petrochemicals", "Pharmaceuticals"],
    applications: ["PTA & VAM production", "Textile dyeing acidulant", "pH regulator", "Food preservative"],
    hazards: "Class 8 Corrosive / Class 3 Flammable",
    unNumber: "UN 2789",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Concentrated organic acid vital for chemical manufacturing, textile processing, and acidity regulation."
  },
  {
    id: "sodium-nitrite",
    name: "Sodium Nitrite 99%",
    chemicalName: "Sodium Nitrite",
    cas: "7632-00-0",
    formula: "NaNO2",
    category: "Industrial Chemicals",
    grade: "Technical Grade",
    purity: "99.0% Min",
    form: "White to Slightly Yellowish Powder",
    packaging: "25kg Woven Bags",
    industries: ["Steel & Galvanizing", "Manufacturing", "Food & Beverage"],
    applications: ["Corrosion inhibition", "Metal heat treatment", "Dye manufacturing", "Meat curing additive"],
    hazards: "Class 5.1 Oxidizer / Class 6.1 Toxic",
    unNumber: "UN 1500",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Effective corrosion inhibitor for closed cooling water loops and heat treatment bath additive."
  },

  // 2. Water Treatment Chemicals
  {
    id: "sodium-metabisulfite",
    name: "Sodium Metabisulfite (SMBS)",
    chemicalName: "Sodium Metabisulfite",
    cas: "7681-57-4",
    formula: "Na2S2O5",
    category: "Water Treatment",
    grade: "Food & Water Treatment Grade",
    purity: "98.0% Min",
    form: "White Crystalline Powder",
    packaging: "25kg Bags / 1,000kg Jumbo Bags",
    industries: ["Water Treatment", "Food & Beverage", "Mining & Minerals", "Oil & Gas"],
    applications: ["Dechlorination in RO plants", "Membrane preservation", "Oxygen scavenger", "Gold flotation reagent"],
    hazards: "Non-hazardous for transport / Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "Essential chemical agent for Reverse Osmosis (RO) desalination plants across KSA. Removes residual free chlorine to protect expensive polyamide membranes from oxidation."
  },
  {
    id: "soda-ash-dense",
    name: "Soda Ash Dense / Light",
    chemicalName: "Sodium Carbonate",
    cas: "497-19-8",
    formula: "Na2CO3",
    category: "Water Treatment",
    grade: "Technical Grade",
    purity: "99.2% Min",
    form: "White Dense Granules or Powder",
    packaging: "25kg / 50kg / 1,000kg Bags",
    industries: ["Water Treatment", "Manufacturing", "Detergents", "Steel & Galvanizing"],
    applications: ["Water softening", "pH elevation", "Glass manufacturing", "Detergent builder"],
    hazards: "Non-hazardous / Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "Crucial alkali builder used to increase water pH, precipitate hardness ions, and act as a key constituent in glass and detergent manufacturing."
  },
  {
    id: "edta-tetrasodium",
    name: "EDTA Tetrasodium Salt (EDTA-4Na)",
    chemicalName: "Tetrasodium Ethylenediaminetetraacetate",
    cas: "64-02-8",
    formula: "C10H12N2Na4O8",
    category: "Water Treatment",
    grade: "Technical / Industrial Grade",
    purity: "99.0% Powder",
    form: "White Powder",
    packaging: "25kg Kraft Paper Bags",
    industries: ["Water Treatment", "Detergents", "Personal Care", "Textiles"],
    applications: ["Chelating agent", "Scale removal", "Water conditioning", "Stabilizer in detergents"],
    hazards: "Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Versatile multi-dentate chelating agent designed to bind polyvalent cations (Ca2+, Mg2+, Fe3+), preventing boiler scaling and soap scum formation."
  },
  {
    id: "sodium-tripolyphosphate-stpp",
    name: "Sodium Tripolyphosphate (STPP)",
    chemicalName: "Pentasodium Triphosphate",
    cas: "7758-29-4",
    formula: "Na5P3O10",
    category: "Water Treatment",
    grade: "Food & Technical Grade",
    purity: "94.0% Min",
    form: "White Fine Powder",
    packaging: "25kg Bags",
    industries: ["Detergents", "Water Treatment", "Food & Beverage"],
    applications: ["Detergent builder", "Water softening agent", "Seafood moisture retention", "Ceramic dispersing agent"],
    hazards: "Non-hazardous",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "High-performance builder and sequestrant used in commercial detergent formulations and municipal water softening."
  },
  {
    id: "polyaluminium-chloride-pac",
    name: "Polyaluminium Chloride (PAC) 30%",
    chemicalName: "Polyaluminium Chloride",
    cas: "1327-41-9",
    formula: "[Al2(OH)nCl6-n]m",
    category: "Water Treatment",
    grade: "Drinking Water Grade",
    purity: "30% Al2O3 Min",
    form: "Yellow Fine Powder",
    packaging: "25kg Bags",
    industries: ["Water Treatment", "Paper & Pulp", "Manufacturing"],
    applications: ["Potable water coagulation", "Industrial wastewater clarification", "Sludge dewatering"],
    hazards: "Non-hazardous / Mild Corrosive",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "Highly efficient inorganic polymer coagulant for municipal drinking water treatment plants and industrial effluent clarification."
  },
  {
    id: "anionic-polyacrylamide-pam",
    name: "Anionic Polyacrylamide (PAM)",
    chemicalName: "Polyacrylamide Anionic",
    cas: "9003-05-8",
    formula: "(C3H5NO)n",
    category: "Water Treatment",
    grade: "Technical Grade",
    purity: "90% Min Active Polymer",
    form: "White Granular Powder",
    packaging: "25kg Kraft Bags",
    industries: ["Water Treatment", "Mining & Minerals", "Oil & Gas"],
    applications: ["Flocculation & sedimentation", "Sludge dewatering", "EOR polymer flooding", "Mining tailing clarification"],
    hazards: "Non-hazardous",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "High-molecular-weight flocculant engineered to rapidly agglomerate suspended solids for fast settling in industrial clarification tanks."
  },

  // 3. Petrochemical & Oilfield Chemicals
  {
    id: "triethylene-glycol-teg",
    name: "Triethylene Glycol (TEG)",
    chemicalName: "Triethylene Glycol",
    cas: "112-27-6",
    formula: "C6H14O4",
    category: "Petrochemical & Oilfield",
    grade: "Oilfield / Gas Dehydration Grade",
    purity: "99.5% Min",
    form: "Viscous Colorless Liquid",
    packaging: "225kg Steel Drums / IBC / ISO Tanker",
    industries: ["Oil & Gas", "Petrochemicals", "Air Treatment"],
    applications: ["Natural gas dehydration", "Gas pipeline drying", "Solvent extraction", "Plasticizer formulation"],
    hazards: "Non-hazardous",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "Industry-standard liquid desiccant for natural gas dehydration systems in Aramco-supplied and GCC gas processing facilities."
  },
  {
    id: "monoethylene-glycol-meg",
    name: "Monoethylene Glycol (MEG)",
    chemicalName: "Ethane-1,2-diol",
    cas: "107-21-1",
    formula: "C2H6O2",
    category: "Petrochemical & Oilfield",
    grade: "Fibre / Technical Grade",
    purity: "99.9% Min",
    form: "Clear Odorless Liquid",
    packaging: "230kg Drums / ISO Tanker",
    industries: ["Petrochemicals", "Oil & Gas", "Construction", "Manufacturing"],
    applications: ["PET resin feedstock", "Coolant & antifreeze", "Gas hydrate inhibitor", "Polyester fibre manufacturing"],
    hazards: "Class 6.1 Harmful if swallowed",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Premium petrochemical intermediate used for polyester fiber production, engine coolants, and gas pipeline hydrate inhibition."
  },
  {
    id: "demulsifier-oilfield",
    name: "Oilfield Demulsifier Concentrate",
    chemicalName: "Proprietary Polyether Formulation",
    cas: "Blend-Demuls-01",
    formula: "Specialty Polymer Blend",
    category: "Petrochemical & Oilfield",
    grade: "Oilfield Speciality",
    purity: "100% Active Concentrate",
    form: "Amber Liquid",
    packaging: "200L Drums / IBC",
    industries: ["Oil & Gas", "Petrochemicals"],
    applications: ["Crude oil emulsion breaking", "Desalting plant additive", "Water-in-oil separation"],
    hazards: "Class 3 Flammable Liquid",
    unNumber: "UN 1993",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "High-speed emulsion breaker formulated to achieve rapid phase separation of water and salts from heavy and light crude oils."
  },

  // 4. Food & Beverage Raw Materials
  {
    id: "citric-acid-anhydrous",
    name: "Citric Acid Anhydrous / Monohydrate",
    chemicalName: "2-hydroxypropane-1,2,3-tricarboxylic acid",
    cas: "77-92-9",
    formula: "C6H8O7",
    category: "Food & Beverage",
    grade: "BP / USP / Food Grade",
    purity: "99.5% - 100.5%",
    form: "White Crystalline Powder",
    packaging: "25kg Multi-wall Paper Bags",
    industries: ["Food & Beverage", "Pharmaceuticals", "Personal Care", "Detergents"],
    applications: ["Acidulant in beverages", "Flavor enhancer", "Preservative", "Antioxidant synergist", "Descaling agent"],
    hazards: "Non-hazardous / Eye Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "FCC/USP food-grade acidulant used widely in Saudi beverage manufacturing, confectionery, pharmaceutical formulations, and industrial chelating applications."
  },
  {
    id: "sodium-bicarbonate-food",
    name: "Sodium Bicarbonate (Baking Soda)",
    chemicalName: "Sodium Hydrogen Carbonate",
    cas: "144-55-8",
    formula: "NaHCO3",
    category: "Food & Beverage",
    grade: "Food / Pharmaceutical Grade",
    purity: "99.0% - 100.5%",
    form: "Fine White Powder",
    packaging: "25kg Bags",
    industries: ["Food & Beverage", "Pharmaceuticals", "Personal Care", "Water Treatment"],
    applications: ["Bakery leavening agent", "Effervescent tablets", "Buffering agent", "Fire extinguisher powder"],
    hazards: "Non-hazardous",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Multi-functional food additive, acid neutralizer, and buffering agent suitable for food processing and pharmaceutical antacids."
  },
  {
    id: "sodium-benzoate",
    name: "Sodium Benzoate Powder",
    chemicalName: "Sodium Benzoate",
    cas: "532-32-1",
    formula: "C7H5NaO2",
    category: "Food & Beverage",
    grade: "FCC / Food Grade",
    purity: "99.0% Min",
    form: "White Granules / Noodle Form",
    packaging: "25kg Bags",
    industries: ["Food & Beverage", "Pharmaceuticals", "Personal Care"],
    applications: ["Antimicrobial food preservative", "Beverage preservation", "Pharmaceutical syrup preservative"],
    hazards: "Non-hazardous / Mild Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Proven preservative that inhibits yeast, mold, and bacterial growth in acidic food, beverage, and personal care products."
  },
  {
    id: "potassium-sorbate",
    name: "Potassium Sorbate Granular",
    chemicalName: "Potassium Sorbate",
    cas: "24634-61-5",
    formula: "C6H7KO2",
    category: "Food & Beverage",
    grade: "FCC / Food Grade",
    purity: "99.0% Min",
    form: "Off-white Spherical Granules",
    packaging: "25kg Cartons",
    industries: ["Food & Beverage", "Personal Care"],
    applications: ["Dairy product preservation", "Bakery shelf-life extension", "Juice preservation", "Cosmetics preservative"],
    hazards: "Non-hazardous",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Highly soluble food-grade preservative effective against mold and yeast in cheeses, bakery items, and beverages."
  },

  // 5. Detergent & Cleaning Raw Materials
  {
    id: "sles-70",
    name: "Sodium Lauryl Ether Sulfate (SLES 70%)",
    chemicalName: "Sodium Laureth Sulfate",
    cas: "68891-38-3",
    formula: "RO(CH2CH2O)nSO3Na",
    category: "Detergent & Cleaning",
    grade: "Cosmetic / Industrial Grade",
    purity: "70% Active Matter",
    form: "Viscous Translucent Paste",
    packaging: "170kg Plastic Drums / 1,000kg IBC",
    industries: ["Detergents", "Personal Care", "Manufacturing"],
    applications: ["Liquid dishwash", "Shampoo & body wash", "Car wash detergents", "Industrial foamer"],
    hazards: "Class 8 Mild Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "Workhorse anionic surfactant providing outstanding foam structure, viscosity response, and grease detergency for personal care and household cleaning."
  },
  {
    id: "capb-30",
    name: "Cocamidopropyl Betaine (CAPB 30%)",
    chemicalName: "Cocamidopropyl Betaine",
    cas: "61789-40-0",
    formula: "C19H38N2O3",
    category: "Detergent & Cleaning",
    grade: "Cosmetic / Technical Grade",
    purity: "30% Active Content",
    form: "Clear Pale Yellow Liquid",
    packaging: "200kg HDPE Drums / IBC",
    industries: ["Personal Care", "Detergents"],
    applications: ["Mild secondary surfactant", "Shampoos & hand wash", "Foam booster", "Antistatic agent"],
    hazards: "Non-hazardous / Mild Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Amphoteric co-surfactant that reduces skin irritation caused by anionic surfactants while boosting flash foam."
  },
  {
    id: "cdea-coconut-diethanolamide",
    name: "Coconut Diethanolamide (CDEA / Coco DEA)",
    chemicalName: "Cocamide DEA",
    cas: "68603-42-9",
    formula: "RCON(CH2CH2OH)2",
    category: "Detergent & Cleaning",
    grade: "Technical / Cosmetic Grade",
    purity: "85% Min Amide Content",
    form: "Viscous Amber Liquid",
    packaging: "200kg Drums",
    industries: ["Detergents", "Personal Care"],
    applications: ["Viscosity builder", "Foam stabilizer", "Superfatting agent in soaps", "Industrial degreasers"],
    hazards: "Mild Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Non-ionic foam booster and thickener essential for liquid detergents, hand soaps, and industrial cleansers."
  },
  {
    id: "glycerin-refined-995",
    name: "Refined Glycerin 99.5% USP",
    chemicalName: "Glycerol",
    cas: "56-81-5",
    formula: "C3H8O3",
    category: "Personal Care",
    grade: "USP / EP / Food Grade (Vegetable Origin)",
    purity: "99.5% Min",
    form: "Clear Viscous Liquid",
    packaging: "250kg Drums / IBC / Bulk Tanker",
    industries: ["Personal Care", "Pharmaceuticals", "Food & Beverage", "Detergents"],
    applications: ["Skin moisturizer / humectant", "Pharmaceutical excipient", "Confectionery solvent", "Resin plasticizer"],
    hazards: "Non-hazardous",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "Pure vegetable-derived USP kosher glycerin offering outstanding humectant, lubricating, and solvent properties."
  },

  // 6. Construction Chemicals
  {
    id: "polycarboxylate-ether-pce",
    name: "Polycarboxylate Ether (PCE Superplasticizer)",
    chemicalName: "Polycarboxylate Ether Polymer",
    cas: "Blend-PCE-01",
    formula: "Modified Polyether Synthetic Polymer",
    category: "Construction Chemicals",
    grade: "Construction Additive Grade",
    purity: "50% Solid Content",
    form: "Pale Yellow Liquid",
    packaging: "210kg Drums / 1,100kg IBC / Bulk Tanker",
    industries: ["Construction", "Manufacturing"],
    applications: ["High-range water reducer for concrete", "Self-consolidating concrete (SCC)", "Precast concrete manufacturing", "High-strength ready mix"],
    hazards: "Non-hazardous",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "Third-generation concrete superplasticizer engineered for extreme water reduction (up to 40%), high slump retention, and high early strength in KSA infrastructure projects."
  },
  {
    id: "snf-naphthalene-superplasticizer",
    name: "Sodium Naphthalene Sulfonate (SNF / PNS)",
    chemicalName: "Sodium Naphthalene Formaldehyde Sulfonate",
    cas: "36290-04-7",
    formula: "(C10H7NaO3S.CH2O)n",
    category: "Construction Chemicals",
    grade: "Construction Grade",
    purity: "92% Powder Min",
    form: "Brown Powder",
    packaging: "25kg Bags",
    industries: ["Construction"],
    applications: ["Standard high-range water reducer", "Tile adhesive additive", "Grout plasticizer"],
    hazards: "Non-hazardous",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Traditional naphthalene-based plasticizer providing strong dispersion and high compressive strength gains."
  },

  // 7. Paint, Adhesive & Coatings
  {
    id: "titanium-dioxide-rutile",
    name: "Titanium Dioxide Rutile Grade (TiO2)",
    chemicalName: "Titanium Dioxide",
    cas: "13463-67-7",
    formula: "TiO2",
    category: "Paint, Adhesive & Coatings",
    grade: "Coatings / Plastics Grade",
    purity: "94.0% TiO2 Min",
    form: "Fine White Powder",
    packaging: "25kg Bags / 1,000kg Jumbo Bags",
    industries: ["Paints & Coatings", "Construction", "Manufacturing"],
    applications: ["White pigment in paints", "Plastic masterbatch opacity", "Architectural coatings", "Paper coating"],
    hazards: "Dust Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "Premium rutile white pigment offering high brightness, superior tinting strength, and exceptional weatherability under desert sunlight."
  },
  {
    id: "epoxy-resin-liquid",
    name: "Liquid Epoxy Resin (Bisphenol A Type)",
    chemicalName: "Bisphenol A Diglycidyl Ether",
    cas: "25068-38-6",
    formula: "(C15H16O2.C3H5ClO)n",
    category: "Paint, Adhesive & Coatings",
    grade: "Technical Coatings Grade",
    purity: "100% Resin (EEW 182-192)",
    form: "Clear Liquid",
    packaging: "220kg Drums / IBC",
    industries: ["Paints & Coatings", "Construction", "Manufacturing"],
    applications: ["Heavy duty anti-corrosion marine coatings", "Industrial floor coatings", "Structural adhesives", "Civil engineering grouts"],
    hazards: "Class 9 Environmentally Hazardous / Skin Sensitizer",
    unNumber: "UN 3082",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Standard liquid epoxy resin for formulating protective industrial floorings, tank linings, and high-performance adhesives."
  },

  // 8. Steel & Galvanizing Chemicals
  {
    id: "hydrochloric-acid-32",
    name: "Hydrochloric Acid 32% (HCl)",
    chemicalName: "Muriatic Acid",
    cas: "7647-01-0",
    formula: "HCl",
    category: "Steel & Galvanizing",
    grade: "Industrial Grade",
    purity: "31.5% - 33.0%",
    form: "Pungent Clear Liquid",
    packaging: "30kg Drums / 1,100kg IBC / Rubber-lined Tanker",
    industries: ["Steel & Galvanizing", "Oil & Gas", "Water Treatment", "Mining & Minerals"],
    applications: ["Steel pickling & rust removal", "Oil well acidizing", "pH control", "Ore processing"],
    hazards: "Class 8 Corrosive",
    unNumber: "UN 1789",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "High-concentration inorganic acid critical for steel pickling lines, hot-dip galvanizing surface preparation, and oilfield matrix stimulation."
  },
  {
    id: "ammonium-chloride",
    name: "Ammonium Chloride 99.5%",
    chemicalName: "Ammonium Chloride",
    cas: "12125-02-9",
    formula: "NH4Cl",
    category: "Steel & Galvanizing",
    grade: "Technical / Galvanizing Grade",
    purity: "99.5% Min",
    form: "White Crystalline Powder",
    packaging: "25kg Bags",
    industries: ["Steel & Galvanizing", "Agriculture", "Pharmaceuticals"],
    applications: ["Flux in hot-dip galvanizing", "Dry cell battery electrolyte", "Metal soldering flux", "Fertilizer component"],
    hazards: "Harmful if swallowed / Eye Irritant",
    unNumber: "N/A",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Essential galvanizing flux component ensuring complete iron surface wetting and oxide removal before zinc immersion."
  },
  {
    id: "zinc-chloride",
    name: "Zinc Chloride Solid / Solution",
    chemicalName: "Zinc Dichloride",
    cas: "7646-85-7",
    formula: "ZnCl2",
    category: "Steel & Galvanizing",
    grade: "Technical Grade",
    purity: "98.0% Min Solid",
    form: "White Deliquescent Powder / Liquid Solution",
    packaging: "25kg Drums / 1,000kg IBC",
    industries: ["Steel & Galvanizing", "Chemical Manufacturing"],
    applications: ["Galvanizing flux additive", "Wood preservation", "Dehydrating agent in chemical synthesis"],
    hazards: "Class 8 Corrosive / Class 9 Marine Pollutant",
    unNumber: "UN 2331",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "High-purity zinc chemical used in hot-dip galvanizing flux formulations to prevent steel oxidation during heating."
  },

  // 9. Mining & Minerals
  {
    id: "sodium-cyanide-solution",
    name: "Sodium Cyanide (For Mining Compliance)",
    chemicalName: "Sodium Cyanide",
    cas: "143-33-9",
    formula: "NaCN",
    category: "Mining & Minerals",
    grade: "Mining Grade (Gold Extraction)",
    purity: "98.0% Min Briquettes",
    form: "White Solid Briquettes",
    packaging: "Plywood Boxes / Steel Drums (Strict Hazmat Escort)",
    industries: ["Mining & Minerals"],
    applications: ["Gold & silver heap leaching", "Precious metal extraction", "Electroplating"],
    hazards: "Class 6.1 Highly Toxic / Toxic Cyanide",
    unNumber: "UN 1689",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: false,
    description: "Strictly regulated mining chemical supplied under SASO and Saudi Security Authority permits for precious metal leaching facilities."
  },

  // 10. Pharmaceutical & Laboratory Reagents
  {
    id: "isopropyl-alcohol-ipa",
    name: "Isopropyl Alcohol 99.9% (IPA)",
    chemicalName: "Isopropanol",
    cas: "67-63-0",
    formula: "C3H8O",
    category: "Pharmaceutical & Laboratory",
    grade: "USP / Electronic / Technical Grade",
    purity: "99.9% Min",
    form: "Colorless Volatile Liquid",
    packaging: "160kg Drums / IBC / ISO Tanker",
    industries: ["Pharmaceuticals", "Personal Care", "Electronics", "Water Treatment"],
    applications: ["Medical disinfectant", "Hand sanitizer formulation", "Electronic circuit cleaning", "Solvent for extraction"],
    hazards: "Class 3 Flammable Liquid",
    unNumber: "UN 1219",
    sdsAvailable: true,
    tdsAvailable: true,
    featured: true,
    description: "High-purity solvent and medical disinfectant widely used in Saudi pharmaceutical manufacturing and electronic component washing."
  }
];
